if( GetLocale() == "deDE") then
	--thanks to Nachti, Thunderhawk2001 and Frontiii for the translations

	MyLocalization = setmetatable(
	  {}, -- empty table
	  {
		__index = function(self, key) -- line 8
		  rawset(self, key, key)
		  return key
		end
	  }
	)

MyLocalization["%s full of %s"] = "%s \195\188ber %s"
MyLocalization["%s has client version %s"] = "%s benutzt die Version %s"
MyLocalization["%s has no seat available for you"] = "%s hat keinen Sitz mehr f\195\188r dich frei."
MyLocalization["%s has seated you in Seat %d"] = "%s hat dich auf Platz %d gesetzt"
MyLocalization["%s is a dealer and has %s seats available"] = "%s ist Kartengeber und hat %s freie Sitzpl\195\164tze."
MyLocalization["%s over %s"] = "%s \195\188ber %s"
MyLocalization["%s sits %s in Seat %d"] = "%s setzt %s auf Platz %d"
MyLocalization["+100 Chips"] = "+100 Chips"
MyLocalization["2 of a Kind"] = "Paar"
MyLocalization["2 Pair"] = "Zwei Paare"
MyLocalization["3 of a Kind"] = "Drilling"
MyLocalization["4 of a Kind"] = "Vierling"
MyLocalization["a Fork of AnzacHoldem"] = "Update von AnzacHoldem"
MyLocalization["Ace"] = "Ass"
MyLocalization["Aces"] = "Asse"
MyLocalization["All In"] = "All In"
MyLocalization["Alliance"] = "Allianz"
--[[Translation missing --]]
MyLocalization["Alliance artwork"] = "Alliance artwork"
MyLocalization["Artwork"] = "Artwork"
MyLocalization["AutoDealing"] = "Automatisches Kartengeben"
MyLocalization["Big Blind"] = "Big Blind"
MyLocalization["Blind increase percent per round"] = "Prozentuale Erh\195\182hung der Blinds pro Runde"
MyLocalization["Blinds"] = "Blinds"
MyLocalization["Boot"] = "Verweisen"
MyLocalization["Call"] = "Mitgehen"
MyLocalization["Call any"] = "Immer mitgehen"
MyLocalization["Called"] = "Mitgegangen"
MyLocalization["Cancel"] = "Abbrechen"
MyLocalization["Cannot boot the dealer."] = "Der Kartengeber kann nicht verwiesen werden."
MyLocalization["Check"] = "Schieben"
MyLocalization["Checked"] = "Geschoben"
MyLocalization["Chips"] = "Chips"
MyLocalization["Clear Chips"] = "Chipreset"
MyLocalization["Current Blind Increment per round"] = "Momentane Erh\195\182hung der Blinds pro Runde"
MyLocalization["Default"] = "Standard"
MyLocalization["Do you wish to start Dealing?"] = "Wollen Sie einen Tisch als Kartengeber er\195\182ffnen?"
MyLocalization["Eight"] = "Acht"
MyLocalization["Eights"] = "Achten"
MyLocalization["Error case"] = "Fehler"
MyLocalization["Feedback: www.FreeHoldemStrategy.com/forum/"] = "Feedback: www.FreeHoldemStrategy.com/forum/"
MyLocalization["Five"] = "F\195\188nf"
MyLocalization["Fives"] = "F\195\188nfen"
MyLocalization["Flush"] = "Flush"
MyLocalization["Flush Straight"] = "Straight Flush"
MyLocalization["Flush: %s high"] = "Flush mit h\195\182chster Karte %s"
MyLocalization["Fold"] = "Passen"
MyLocalization["Folded"] = "Gepasst"
MyLocalization["Four"] = "Vier"
MyLocalization["Fours"] = "Vieren"
MyLocalization["Full House"] = "Full House"
MyLocalization["has left the table."] = "hat den Tisch verlassen."
MyLocalization["has quit. GG."] = "hat das Spiel verlassen. GG."
MyLocalization["High Card"] = "H\195\182chste Karte"
MyLocalization["Horde"] = "Horde"
--[[Translation missing --]]
MyLocalization["Horde artwork"] = "Horde artwork"
MyLocalization["I'm Back"] = "Re"
MyLocalization["Jack"] = "Bube"
MyLocalization["Jacks"] = "Buben"
MyLocalization["King"] = "K\195\182nig"
MyLocalization["Kings"] = "K\195\182nige"
MyLocalization["Learn How to Play Texas Holdem"] = "Lerne Texas Holdem zu spielen"
MyLocalization["Looking for clients"] = "Suche nach Mitspielern."
MyLocalization["Looking for dealers"] = "Suche nach Kartengebern."
MyLocalization["Minimap Icon"] = "Minimap Symbol"
MyLocalization["Neutral"] = "Neutral"
--[[Translation missing --]]
MyLocalization["Neutral artwork"] = "Neutral artwork"
MyLocalization["Next Round's Big Blind"] = "Big Blind der n\195\164chsten Runde"
MyLocalization["Nine"] = "Neun"
MyLocalization["Nines"] = "Neunen"
MyLocalization["No such player"] = "Spieler existiert nicht"
MyLocalization["No Winners. Game Seed = "] = "Keine Gewinner. Game Seed = "
MyLocalization["Ok"] = "Best\195\164tigen"
MyLocalization["Options"] = "Optionen"
MyLocalization["Original"] = "Original"
--[[Translation missing --]]
MyLocalization["Original artwork"] = "Original artwork"
MyLocalization["Play"] = "Spielen"
MyLocalization["Player Invalid Action"] = "Ung\195\188ltige Spieleraktion"
MyLocalization["Playing"] = "Spielt"
MyLocalization["Queen"] = "Dame"
MyLocalization["Queens"] = "Damen"
MyLocalization["Quit"] = "Spiel verlassen"
MyLocalization["Raise"] = "Erh\195\182hen"
MyLocalization["Raised"] = "Erh\195\182ht"
MyLocalization["Royal Flush"] = "Royal Flush"
MyLocalization["Select card back artwork"] = "W\195\164hle das Artwork des Kartenr\195\188ckens"
MyLocalization["Set the by what percent the Blind increases each round"] = "Lege fest, um wie viel Prozent die Blinds jede Runde erh\195\182ht werden sollen"
MyLocalization["Set the starting Blind"] = "Lege den Ersten Blind fest"
MyLocalization["Set the starting Chips"] = "Lege die Anzahl der Anfangschips fest"
MyLocalization["Seven"] = "Sieben"
MyLocalization["Sevens"] = "Siebenen"
MyLocalization["Show Cards"] = "Karten zeigen"
MyLocalization["Showdown"] = "Aufdecken"
MyLocalization["Showing"] = "Aufgedeckt"
MyLocalization["Sit Out"] = "Aussetzen"
MyLocalization["Sitting Out"] = "Setzt aus"
MyLocalization["Six"] = "Sechs"
MyLocalization["Sixes"] = "Sechsen"
MyLocalization["Small Blind"] = "Small Blind"
MyLocalization["Sorry the dealer can not sit out.  Set your chips to Zero to enable auto deal."] = "Der Dealer kann nicht aussetzen.  Setze deine Chips auf 0 um Autodealing zu aktivieren."
MyLocalization["Split"] = "Unentschieden"
MyLocalization["Start Dealing"] = "Kartengeber"
MyLocalization["Starting Blind"] = "Erster Blind"
MyLocalization["Starting Chips"] = "Anfangschips"
MyLocalization["Sticky"] = "Festgesetzt"
MyLocalization["Straight"] = "Stra\195\159e"
MyLocalization["Straight Flush to the %s"] = "Straight Flush mit h\195\182chster Karte %s"
MyLocalization["Straight to the %s"] = "Stra\195\159e mit h\195\182chster Karte %s"
MyLocalization["Ten"] = "Zehn"
MyLocalization["Tens"] = "Zehnen"
MyLocalization["The dealer booted you."] = "Der Kartengeber hat dich verwiesen."
MyLocalization["These options are saved between sessions"] = "Diese Optionen werden zwischen zwei Sessions gespeichert."
MyLocalization["Three"] = "Drei"
MyLocalization["Threes"] = "Dreien"
MyLocalization["Tick to act automatically"] = "Markieren, um automatisch zu agieren"
MyLocalization["To join a game use '/holdem dealer <playername>'"] = "Um einem anderen Spiel beizutreten, geben Sie '/holdem dealer <Spielername>' ein"
MyLocalization["Total Pot"] = "Insgesamt im Pot"
MyLocalization["Turn minimap icon on/off"] = "Minimap Symbol an/aus schalten."
MyLocalization["Two"] = "Zwei"
MyLocalization["Twos"] = "Zweien"
MyLocalization["Use '/holdem artwork <number>' to set artwork."] = "Benutze '/holdem artwork <Zahl>' um die Darstellung zu \195\164ndern."
MyLocalization["Use '/holdem blind <number>' to set starting blind."] = "Benutze '/holdem blind <Zahl>' um den ersten Blind festzulegen."
MyLocalization["Use '/holdem clients' to find clients in your guild/party/raid."] = "Benutze '/holdem clients' um Mitspieler in deiner Gilde/Gruppe/Raid zu finden."
MyLocalization["Use '/holdem dealer <playername>' to join someone elses table."] = "Benutze '/holdem dealer <Spielername>' um einem anderen Tisch beizutreten."
MyLocalization["Use '/holdem dealers' to find dealers in your guild/party/raid."] = "Benutze '/holdem dealers' um Kartengeber in deiner Gilde/Gruppe/Raid zu finden."
MyLocalization["Use '/holdem help' for slash command options"] = "Benutze '/holdem help' um die Hilfe aufzurufen."
MyLocalization["Use '/holdem increase <percent>' to set blind increment percent."] = "Benutze '/holdem increase <Prozent>' um die prozentuale Erh\195\182hung der Blinds festzulegen."
MyLocalization["Use '/holdem options' for options panel"] = "Benutze '/holdem options' um das Optionsfenster zu \195\182ffnen."
MyLocalization["Use '/holdem' to start a table as the dealer."] = "Benutze '/holdem' um einen Tisch als Kartengeber zu er\195\182ffnen."
--[[Translation missing --]]
MyLocalization["Use Alliance card back artwork"] = "Use Alliance card back artwork"
--[[Translation missing --]]
MyLocalization["Use Horde card back artwork"] = "Use Horde card back artwork"
MyLocalization["Use just /holdem instead"] = "Benutze einfach /holdem stattdessen"
--[[Translation missing --]]
MyLocalization["Use neutral card back artwork"] = "Use neutral card back artwork"
--[[Translation missing --]]
MyLocalization["Use original card back artwork"] = "Use original card back artwork"
MyLocalization["Winner!"] = "Sieger!"
MyLocalization["wins"] = "gewinnt"
MyLocalization["WoW Texas Hold'em"] = "WoW Texas Hold'em"
MyLocalization["WoW Texas Hold'em Options"] = "WoW Texas Hold'em Optionen"
MyLocalization["You are now a dealer."] = "Du bist nun Kartengeber."
MyLocalization["You cannot show your cards until the hand is over"] = "Sie k\195\182nnen nicht Ihre Karten zeigen, bis die Hand \195\188ber"
MyLocalization["You did not act in time. Press I'm Back to continue playing."] = "Du hast nicht rechtzeitig gehandelt. Dr\195\188cke Re um weiterzuspielen."
MyLocalization["Your turn"] = "Dein Zug."


end
